FROM golang:1.24.2-alpine3.21 AS compiler

ARG PING_PORT="8080"
ENV PING_PORT=$PING_PORT

WORKDIR /compile

COPY . .

RUN go build -o /compile/api

FROM alpine:3.21 AS image

ARG BUILD_VERSION="latest"

LABEL version="$BUILD_VERSION"
LABEL authors="noahlehmann"

COPY --from=compiler /compile/api /app/api

EXPOSE 8080
CMD ["/app/api"]

